FROM php:8.1.7-fpm-alpine

LABEL maintainer="Nazar Taran"

WORKDIR /var/www/studcab-back

COPY --from=composer:latest /usr/bin/composer /usr/local/bin/composer
COPY php.ini /usr/local/etc/php/
RUN docker-php-ext-install -j$(nproc) pdo_mysql

RUN set -x ; \
    addgroup -g 82 -S www-data ; \
    adduser -u 82 -D -S -G www-data www-data ; exit 0

CMD rm -rf ./vendor && \
    chown -R www-data:www-data /var/www/studcab-back && \
    composer install --no-dev && \
    php artisan key:generate && \
    php-fpm
